### ISSUE TITLE
Outdated?

### ISSUE THREAD

**Issue by DigitalFlow** [rjz/typescript-react-redux#36]
Hey there,

thanks for your sample.

As it seems, some things slightly shifted in new redux releases. The Dispatch function for example now want s an AnyAction as generic parameter, which leads to the samples showing errors, that our Action interface is missing a "type" property.
This is also an issue that is shown in Visual Studio Code directly after checking out this repo, but not for redux.Dispatch<Action> and instead in the calls to dispatch inside the component.

It's also rather unfortunate that the code in here is very much different to your blog post, especially the definition of the Action types.
Nonetheless it helped me a lot, thanks.

Kind Regards,
Florian

**Comment by rjz** [comment]
Thanks, @DigitalFlow!

> which leads to the samples showing errors

This seems to be related to how this project used (abused?) thunk actions, that should be solvable by [invoking action-creators immediately](https://github.com/rjz/typescript-react-redux/pull/37/files#diff-2111da328f93f378507bff6b253c1ddaR46) rather than waiting for `redux-thunk` to invoke them. If you have a moment to confirm that #37 addresses the issue, I'll get it merged up to hopefully save others some trouble.

> the code in here is very much different to your blog post, especially the definition of the Action types.

Both this demo and its various dependencies have evolved quite a bit. I've tried to [tie "formative" posts back to the related commits](https://github.com/rjz/typescript-react-redux#typescript--react--redux) but it can certainly feel confusing. I would be very open to thoughts or suggestions on how to make either the posts or the code here more approachable, though!

**Comment by DigitalFlow** [comment]
Hey @rjz,

thanks for your quick response.
Yes, your update in #37 addressed the issue, everything is fine now on branch `upgrade-deps`.

Kind Regards,
Florian

**Comment by rjz** [comment]
Perfect. Thanks again for reporting, Florian, and please reach out if you run into any other issues!
